#!/bin/bash

echo "Enabling RPi-Display on this installation of OctoPi, do not turn off your Pi during this process!"
sudo sed -i 's/^blacklist spi-bcm2708/#blacklist spi-bcm2708/g' /etc/modprobe.d/raspi-blacklist.conf
sudo REPO_URI=https://github.com/notro/rpi-firmware BRANCH=builtin rpi-update

if [ ! -f /boot/cmdline.txt.bak ]; then
    sudo cp /boot/cmdline.txt /boot/cmdline.txt.bak
fi
sudo cp /boot/cmdline-pi-tft.txt /boot/cmdline.txt

if ! `grep --quiet ads7846_device /etc/modules`; then
    echo "ads7846_device model=7846 cs=1 gpio_pendown=25 speed=2000000 keep_vref_on=1 swap_xy=1 pressure_max=255 x_plate_ohms=60 x_min=200 x_max=3900 y_min=200 y_max=3900" | sudo tee --append /etc/modules > /dev/null; 
fi
