#!/bin/bash

PACKAGE="xbindkeys"

# Starting xbindkeys if is installed
if apt list --installed "$PACKAGE" | grep -q "[installed]"; then
    # Define the path to our custom config file (relative to the script)
    DISABLE_CONFIG_PATH="/boot/firmware/xbindkeys_disable.conf"
    # Define the path to the user's xbindkeysrc file
    XBINDKEYS_RC="/home/$BASE_USER/.xbindkeysrc"

    # Function to generate the xbindkeysrc file based on our config
    generate_xbindkeysrc() {
        local config_path=$1
        local output_path="$XBINDKEYS_RC"

        # Create a temporary xbindkeys config file
        local temp_file="/tmp/xbindkeysrc.temp"
        > "$temp_file" # Clear the file

        # Read each line from the config file and format it for xbindkeysrc
        while IFS= read -r combo; do
            # Skip empty or commented lines
            if [[ -z "$combo" || "$combo" =~ ^# ]]; then
                continue
            fi
            echo "\"echo\"" >> "$temp_file"
            echo "  $combo" >> "$temp_file"
            echo >> "$temp_file"
        done < "$config_path"

        # Copy the temporary file to the user's home directory
        cp "$temp_file" "$output_path"
        #chown "$user":"$user" "$output_path"
        rm "$temp_file"
    }
    echo "$PACKAGE is installed so starting the package!"
    generate_xbindkeysrc "$DISABLE_CONFIG_PATH"
    xbindkeys &
fi

flags=(
   --kiosk
   --touch-events=enabled
   --disable-pinch
   --noerrdialogs
   --no-memcheck
   --disable-session-crashed-bubble
   --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'
   --disable-component-update
   --overscroll-history-navigation=0
   --disable-features=TranslateUI
   --autoplay-policy=no-user-gesture-required
   --disk-cache-size=500000000
)

# Standard behavior - runs chromium
chromium-browser "${flags[@]}" --app=$(/opt/custompios/scripts/get_url)
exit;

# Remove the two lines above to enable signage mode - refresh the browser whenever errors are seen in log

chromium-browser --enable-logging --log-level=2 --v=0 "${flags[@]}" --app=$(/opt/custompios/scripts/get_url) &

export logfile="/home/$(id -nu 1000)/.config/chromium/chrome_debug.log"


# Refreshes after a crash by watching logs
tail -n 0 -F "$logfile" | while read LOGLINE &> /dev/null; do

   echo "Refreshing after crash"
   echo "Restarting at `date` after a reported crash. Logline: ${LOGLINE}" >> /tmp/crashlog
   [[ ("${LOGLINE}" == *"ERROR"*) || ("${LOGLINE}" == *"FATAL"*) ]] && /home/$(id -nu 1000)/scripts/refresh

done
