F11
F12
control + n
control + w
control + t
control + j
control + h
control + o
control + p
control + s
control + 2
control + 3
control + 4
control + 5
control + 6
control + 7
control + 8
control + 9
control + tab
control + alt + x
control + pagedown
control + shift + tab
control + pageup
control + shift + t
control+shift + N
control+shift + n
control + shift + i
control + shift + j
control + shift + c