Vagrant.configure("2") do |o|
    # o.vm.box = "fullpageos-build"
    o.vm.box= "https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/15.04/ubuntu-15.04-amd64.box"
    o.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    o.vm.synced_folder "../../", "/FullPageOS", create:true, type: "nfs"
    o.vm.network :private_network, ip: "192.168.55.55"
    o.vm.provision :shell, :path => "setup.sh", args: ENV['SHELL_ARGS']

end
