#!/bin/bash

while true
do
    if [[ $(curl -sL -b cookiefile -w "%{http_code}\\n" "$(/home/pi/scripts/get_url)" -o /dev/null) =~ ^([23][0-9]{2,2}|401)$ ]] || grep -q disabled "/boot/check_for_httpd" ; then
      xdotool mousemove 9000 9000
      %BROWSER_START_SCRIPT%
    fi
    sleep 1
done
