#!/bin/bash

SERIAL=`cat /proc/cpuinfo | perl -n -e '/^Serial[ ]*: ([0-9a-f]{16})$/ && print "$1\n"'`

# Standard behavior - runs chrome
chromium-browser --kiosk --touch-events=enabled --disable-pinch --noerrdialogs --disable-session-crashed-bubble --app=$(head -n 1 /boot/fullpageos.txt | sed -e "s/{serial}/${SERIAL}/g")
exit;

# Remove the two lines above to enable signage mode - refresh the browser whenever errors are seen in log

chromium-browser --enable-logging --v=1 --kiosk --touch-events=enabled --disable-pinch --noerrdialogs --disable-session-crashed-bubble --app=$(head -n 1 /boot/fullpageos.txt | sed -e "s/{serial}/${SERIAL}/g") &

export logfile="/home/pi/.config/chromium/chrome_debug.log"


# Refreshes after a crash by watching logs
tail -n 0 -f "$logfile" | while read LOGLINE &> /dev/null; do

   echo "Refreshing after crash"
   echo "Restarting at `date` after a reported crash. Logline: ${LOGLINE}" >> /tmp/crashlog
   [[ "${LOGLINE}" == *"ERROR"* ]] && /home/pi/scripts/refresh

done
