#!/bin/bash -x
whoami
FULLPAGEOSPATH=/FullPageOS

#Update repos used
#sudo -u guy /home/guy/stuff/scripts/gitmirror/update_git_mirrors

for i in `lsof ${FULLPAGEOSPATH}/src/workspace/mount | awk '{print $2}'`; do kill -9 $i; done

rm ${FULLPAGEOSPATH}/src/workspace/*.img
rm ${FULLPAGEOSPATH}/src/workspace/*.zip

pushd ${FULLPAGEOSPATH}
    umount ${FULLPAGEOSPATH}/src/workspace/mount/boot
    umount ${FULLPAGEOSPATH}/src/workspace/mount/dev/pts
    umount ${FULLPAGEOSPATH}/src/workspace/mount
    git pull origin devel
    
    ${FULLPAGEOSPATH}/src/build $1
    pushd src
    ${FULLPAGEOSPATH}/src/release $1
    popd
    chmod 777 ${FULLPAGEOSPATH}/src/*
popd
