#!/bin/bash -x
whoami
OCTOPIPATH=/home/guy/tmp/OctoPi

#Update repos used
sudo -u guy /home/guy/stuff/scripts/gitmirror/update_git_mirrors

for i in `lsof ${OCTOPIPATH}/src/workspace/mount | awk '{print $2}'`; do kill -9 $i; done

rm ${OCTOPIPATH}/src/workspace/*.img
rm ${OCTOPIPATH}/src/workspace/*.zip

pushd ${OCTOPIPATH}
    umount ${OCTOPIPATH}/src/workspace/mount/boot
    umount ${OCTOPIPATH}/src/workspace/mount
    git pull origin devel
    export OCTOPI_OCTOPRINT_REPO_BUILD='http://localhost/git/OctoPrint.git/'
    export OCTOPI_OCTOPIPANEL_REPO_BUILD='http://localhost/git/OctoPiPanel.git/'
    export OCTOPI_FBCP_REPO_BUILD='http://localhost/git/rpi-fbcp.git/'
    export OCTOPI_MJPGSTREAMER_REPO_BUILD='http://localhost/git/mjpg-streamer.git/'
    
    ${OCTOPIPATH}/src/build $1
    pushd src
    ${OCTOPIPATH}/src/release $1
    popd
    chmod 777 ${OCTOPIPATH}/src/*
popd
