#!/bin/bash
MIRROR_LOCATION=/var/www/git
mkdir $MIRROR_LOCATION
pushd MIRROR_LOCATION
    for repo in `ls`
    do
        pushd $repo
            git fetch --prune
            git update-server-info
        popd
    done
popd
