#!/bin/bash

echo ""
echo "Installing Adafruit PiTFT Display on this installation of OctoPi, do not turn off your Pi during this process!"
echo ""

cd ~
mkdir pitft
cd pitft

wget http://adafru.it/pitftsh
mv pitftsh pitft.sh
chmod +x pitft.sh

sudo ./pitft.sh -t 28r -r

cd ~
sudo rm pitft -R

echo ""
echo "Reboot you Pi to use the Adafruit Pi TFT Display"
echo ""
