#!/bin/bash
keyfile=/etc/ssl/private/ssl-cert-snakeoil.key
pemfile=/etc/ssl/certs/ssl-cert-snakeoil.pem
certfile=/etc/ssl/snakeoil.pem

if [ ! -f $keyfile ] || [ ! -s $keyfile ] || [ ! -f $pemfile ] || [ ! -s $pemfile ] || [ ! -f $certfile ] || [ ! -s $certfile ]; then
    echo "Generating SSL certificate"
    sudo make-ssl-cert generate-default-snakeoil --force-overwrite 
    sudo cat $keyfile $pemfile > $certfile
fi
