#!/usr/bin/env bash

# make sure to export all the variables to make them available to the chroot scripts as well

# customize the hostname 
export OVERRIDE_HOSTNAME=blueberrypi

# skip octoprint installation in main build script 
export OVERRIDE_OCTOPRINT=yes
