#!/usr/bin/env bash

BUILD_SCRIPT__PATH=$(dirname $(realpath -s $BASH_SOURCE))
source ${BUILD_SCRIPT__PATH}/common.sh

OCTOPI_PATH=$(dirname $(realpath -s $0))

BUILD_VARIANT=default
BUILD_FLAVOR=default

if [ "$#" -gt 0 ]; then
  BUILD_VARIANT=$1
fi
if [ "$#" -gt 1 ]; then
  BUILD_FLAVOR=$2
fi

if [ $BUILD_VARIANT != 'default' ]; then
  export VARIANT_BASE="$OCTOPI_PATH/variants/$BUILD_VARIANT"
  [ -d $VARIANT_BASE ] || die "Could not find Variant $BUILD_VARIANT"
  if [ $BUILD_FLAVOR == '' ] || [ $BUILD_FLAVOR == 'default' ]; then
    FLAVOR_CONFIG=$VARIANT_BASE/config
  else
    FLAVOR_CONFIG=$VARIANT_BASE/config.$BUILD_FLAVOR
  fi
  source $FLAVOR_CONFIG || die "Could not find config file $FLAVOR_CONFIG"
fi

echo -e "--> Building VARIANT $BUILD_VARIANT, FLAVOR $BUILD_FLAVOR"

source $OCTOPI_PATH/config
source $OCTOPI_PATH/octopi
