#!/usr/bin/env bash
set -x
# OctoPI generation script
# Helper script that runs in a Raspbian chroot to create the OctoPI distro
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
fixLd(){
  sed -i 's@/usr/lib/arm-linux-gnueabihf/libcofi_rpi.so@\#/usr/lib/arm-linux-gnueabihf/libcofi_rpi.so@' /etc/ld.so.preload
}

unpackHome(){
  chown -hR pi /filesystem/home
  chgrp -hR pi /filesystem/home
  cp -av /filesystem/home/* /home/pi
  cp -av /filesystem/home/.* /home/pi
}

unpackRoot(){
  cp -av /filesystem/root/* /
}

unpackBoot(){
  cp -av /filesystem/boot/* /boot
}

fixLd
unpackHome
unpackBoot
apt-get update

apt-get remove -y --purge scratch squeak-plugins-scratch squeak-vm

#apt-get octoprint virtualenv
apt-get -y install python-virtualenv python-dev git python-numpy

pushd /home/pi
  
  #Get octopi and mjpg-streamer
  sudo -u pi git clone https://github.com/foosel/OctoPrint.git

  #build virtualenv
  sudo -u pi virtualenv --system-site-packages oprint
  
  sudo -u pi oprint/bin/pip install -r /home/pi/OctoPrint/requirements.txt
  sudo -u pi oprint/bin/pip install -r /home/pi/OctoPrint/requirements.txt

  #taken from octoprint website:
  sudo usermod -a -G tty pi
  sudo usermod -a -G dialout pi
      
  #mjpg-streamer
  sudo apt-get -y install subversion libjpeg8-dev imagemagick libav-tools cmake
  sudo -u pi git clone https://github.com/jacksonliam/mjpg-streamer.git
  pushd mjpg-streamer
    mv mjpg-streamer-experimental/* .
    sudo -u pi make
  popd
  
  #Add pyserial that can handle non-standard baud rates
  sudo -u pi svn co http://pyserial.svn.sourceforge.net/svnroot/pyserial/trunk pyserial
  pushd pyserial
      sudo -u pi wget http://sourceforge.net/p/pyserial/patches/_discuss/thread/ed3fb0de/f4fd/attachment/pyserial.patch
      sudo -u pi patch -p0 < pyserial.patch
      pushd pyserial
          sudo -u pi /home/pi/oprint/bin/python setup.py install
      popd
  popd
  
  #make autostart scripts
  pushd scripts
    chmod 755 octoPrintStart
    chmod 755 webcamDaemon
    chmod 755 genCert
  popd
  
#setup haproxy for http and https, and webcam
export HAPROXY_VERSION=1.5-dev19
sudo apt-get -y install ssl-cert libssl-dev libpcre3-dev checkinstall
rm /etc/ssl/private/ssl-cert-snakeoil.key /etc/ssl/certs/ssl-cert-snakeoil.pem
sudo -u pi wget http://haproxy.1wt.eu/download/1.5/src/devel/haproxy-${HAPROXY_VERSION}.tar.gz
sudo -u pi tar xzvf haproxy-${HAPROXY_VERSION}.tar.gz
rm haproxy-${HAPROXY_VERSION}.tar.gz
sudo -u pi mv `ls | grep haproxy | head -n 1` haproxy-ss
pushd haproxy-ss
    sudo -u pi make TARGET=linux2628 USE_LINUX_SPLICE=1 USE_LINUX_TPROXY=1 USE_PCRE=1 USE_OPENSSL=1
    mkdir -p /usr/local/share/man/man1 /usr/local/doc /usr/local/doc/haproxy
    sudo checkinstall --default --pkgname haproxy --pkgversion 1.5
popd
rm -rf haproxy-ss

adduser --system --disabled-password --disabled-login --home /var/lib/haproxy \
        --no-create-home --quiet --force-badname --group haproxy

popd

sed -i 's@exit 0@@' /etc/rc.local

echo "Make Octoprint avilable on port 80"
echo "echo \"1\" > /proc/sys/net/ipv4/conf/all/forwarding" >> /etc/rc.local
echo "iptables -t nat -A POSTROUTING -o all -j MASQUERADE" >> /etc/rc.local
echo "" >> /etc/rc.local

echo "/home/pi/scripts/genCert" >> /etc/rc.local
echo "sudo -u pi /home/pi/scripts/octoPrintStart" >> /etc/rc.local
echo "sudo -u pi /home/pi/scripts/webcamDaemon &" >> /etc/rc.local
echo "/usr/local/sbin/haproxy -f /etc/haproxy/haproxy.cfg" >> /etc/rc.local
echo "exit 0" >> /etc/rc.local

#automatic startup
echo "pi ALL=NOPASSWD: /sbin/shutdown" > /etc/sudoers.d/octoprint-shutdown

#reach printer by name
sudo apt-get -y install avahi-daemon
echo octopi > /etc/hostname
sed -i 's@raspberrypi@octopi@' /etc/hosts

# enable raspicam
echo "# enable raspicam" >> /boot/config.txt
echo "start_x=1" >> /boot/config.txt
echo "gpu_mem=128" >> /boot/config.txt

#unpack root in the end, so etc file are not overwritten, might need to add two roots int he future
unpackRoot

#cleanup
fixLd
sudo apt-get clean

sed -i 's@\#/usr/lib/arm-linux-gnueabihf/libcofi_rpi.so@/usr/lib/arm-linux-gnueabihf/libcofi_rpi.so@' /etc/ld.so.preload
