#!/usr/bin/env bash
# FullPageOS generation script
# This script takes a Raspbian image and adds to it octoprint and verions addons
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3

source $FULLPAGEOS_SCRIPT_PATH/common.sh

function execute_chroot_script() {
  #move FullPageOS filesystem files
  cp -vr --preserve=mode,timestamps $1/filesystem .

  #black magic of qemu-arm-static
  cp `which qemu-arm-static` usr/bin
  
  cp $2 chroot_script
  chmod 755 chroot_script
  cp $FULLPAGEOS_SCRIPT_PATH/common.sh common.sh
  chmod 755 common.sh
  
  chroot . usr/bin/qemu-arm-static /bin/bash /chroot_script
  
  #cleanup
  rm chroot_script
  rm -rfv filesystem
}

mkdir -p $FULLPAGEOS_WORKSPACE
mkdir -p $FULLPAGEOS_MOUNT_PATH

install_cleanup_trap
install_fail_on_error_trap $FULLPAGEOS_MOUNT_PATH
unmount_image $FULLPAGEOS_MOUNT_PATH force || true

pushd $FULLPAGEOS_WORKSPACE
  if [ -e *.img ]; then  
    rm *.img
  fi
  unzip $FULLPAGEOS_ZIP_IMG
  FULLPAGEOS_IMG_PATH=`ls | grep .img`
  export FULLPAGEOS_BUILDBASE=$(basename $FULLPAGEOS_IMG_PATH)

  if [ -n "$FULLPAGEOS_IMAGE_ENLARGEROOT" ]
  then
    # make our image a bit larger so we don't run into size problems...
    enlarge_ext $FULLPAGEOS_IMG_PATH 2 $FULLPAGEOS_IMAGE_ENLARGEROOT
  fi

  # mount root and boot partition
  mount_image $FULLPAGEOS_IMG_PATH $FULLPAGEOS_MOUNT_PATH
  if [ -n "$FULLPAGEOS_APT_CACHE" ]
  then
    mkdir -p "$FULLPAGEOS_APT_CACHE"
    mount --bind "$FULLPAGEOS_APT_CACHE" $FULLPAGEOS_MOUNT_PATH/var/cache/apt
  fi

  #Edit pi filesystem
  pushd $FULLPAGEOS_MOUNT_PATH

    #make QEMU boot (remember to return)
    fixLd
    #sed -i 's@include /etc/ld.so.conf.d/\*.conf@\#include /etc/ld.so.conf.d/\*.conf@' etc/ld.so.conf

    # if an additional pre-script is defined, execute that now
    if [ -n "$FULLPAGEOS_PRESCRIPT" ] && [ -f $FULLPAGEOS_PRESCRIPT/chroot_script ]; then
      echo "Injecting environment pre script from $FULLPAGEOS_PRESCRIPT..."
      execute_chroot_script $FULLPAGEOS_PRESCRIPT $FULLPAGEOS_PRESCRIPT/chroot_script
    fi

    # if building a variant, execute its pre-chroot script
    if [ -n "$VARIANT_BASE" ] && [ -f $VARIANT_BASE/pre_chroot_script ]; then
      echo "Injecting variant pre script from $VARIANT_BASE..."
      execute_chroot_script $VARIANT_BASE $VARIANT_BASE/pre_chroot_script
    fi
 
    # execute the base chroot script
    execute_chroot_script $FULLPAGEOS_SCRIPT_PATH $FULLPAGEOS_CHROOT_SCRIPT_PATH
    
    # if building a variant, execute its post-chroot script
    if [ -n "$VARIANT_BASE" ] && [ -f $VARIANT_BASE/post_chroot_script ]; then
      echo "Injecting variant post script from $VARIANT_BASE..."
      execute_chroot_script $VARIANT_BASE $VARIANT_BASE/post_chroot_script
    fi

    # if an additional post-script is defined, execute that now
    if [ -n "$FULLPAGEOS_POSTSCRIPT" ] && [ -f $FULLPAGEOS_POSTSCRIPT/chroot_script ]; then
      echo "Injecting environment post script from $FULLPAGEOS_POSTSCRIPT..."
      execute_chroot_script $FULLPAGEOS_POSTSCRIPT $FULLPAGEOS_POSTSCRIPT/chroot_script
    fi

    restoreLd
  popd
  
  # unmount first boot, then root partition
  unmount_image $FULLPAGEOS_MOUNT_PATH
  chmod 777 $FULLPAGEOS_IMG_PATH

  if [ -n "$FULLPAGEOS_IMAGE_RESIZEROOT" ]
  then
    # resize image to minimal size + provided size
    minimize_ext $FULLPAGEOS_IMG_PATH 2 $FULLPAGEOS_IMAGE_RESIZEROOT
  fi
popd

