#!/usr/bin/env bash
# OctoPi generation script
# This script takes a Raspbian image and adds to it octoprint and verions addons
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
ZIP_IMG=`dirname $0`/2013-05-25-wheezy-raspbian.zip
WORKSPCE=`dirname $0`/workspace
CHTOOT_SCRIPT_PATH=`dirname $0`/chroot_script
MOUNT_PATH=$WORKSPCE/mount
mkdir -p $WORKSPCE
mkdir -p $MOUNT_PATH
pushd $WORKSPCE
rm *.img
unzip $ZIP_IMG
IMG_PATH=`ls  | grep .img`
sudo mount -t ext4 -o loop,offset=62914560 $IMG_PATH $MOUNT_PATH

  #Edit pi filesystem
  pushd $MOUNT_PATH

#make QEMU boot (remember to return)
#sed -i 's@include /etc/ld.so.conf.d/\*.conf@\#include /etc/ld.so.conf.d/\*.conf@' etc/ld.so.conf


#black magic of qemu-arm-static
cp `which qemu-arm-static` usr/bin
cp $CHTOOT_SCRIPT_PATH chroot_script
chmod 755 chroot_script

chroot . usr/bin/qemu-arm-static /bin/bash /chroot_script

rm chroot_script
rm usr/bin/qemu-arm-static
popd

sudo umount $MOUNT_PATH
chmod 777 $IMG_PATH
popd

