#!/usr/bin/env bash
if [ -z "$1" ];then
    pushd workspace
else
    pushd workspace-$1
fi

FILENAME=$(basename `ls . |  grep .img | tail -n 1` .img)  
FULLPAGEOS_FILENAME=$(echo $FILENAME-`cat ../filesystem/root/etc/fullpageos_version` | sed 's/raspbian/fullpageos/')
mv ${FILENAME}.img $FULLPAGEOS_FILENAME.img
zip $FULLPAGEOS_FILENAME.zip $FULLPAGEOS_FILENAME.img

popd
